name: Test, Build and Deploy Images


on:
    pull_request:
    push:

jobs:
  python-tests:
    runs-on: ubuntu-latest

    env:
      python-version: 3.9 # Our base image has Python 3.9

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel # wheel need to be installed before mavproxy
        pip install pylint mypy isort black \

    - name: Run tests
      run: |
        ./.hooks/pre-push
